### ISSUE TITLE
Error when starting server.js

### ISSUE THREAD

**Issue by ozkanaltuner** [IBM-Bluemix/HybridBanking-FeedbackManager#1]
Hi, 

I got following error when trying to run the sample. What could be the possible reason? 

```
2015-11-18T19:23:43.62+0200 [DEA/117]    OUT Starting app instance (index 0) with guid 53bbcba6-019a-4ffd-ba90-4e24d9aab466
2015-11-18T19:23:54.86+0200 [App/0]      OUT Detected 1024 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-11-18T19:23:54.86+0200 [App/0]      OUT Recommending WEB_CONCURRENCY=2
2015-11-18T19:23:55.65+0200 [App/0]      OUT > locallaunch@1.0.0 start /home/vcap/app
2015-11-18T19:23:55.65+0200 [App/0]      OUT > node server.js
2015-11-18T19:23:56.39+0200 [App/0]      ERR /home/vcap/app/node_modules/node-env-file/lib/index.js:130
2015-11-18T19:23:56.39+0200 [App/0]      ERR             throw new TypeError("Environment file doesn't exist: " + env_file)
2015-11-18T19:23:56.39+0200 [App/0]      ERR                   ^
2015-11-18T19:23:56.39+0200 [App/0]      ERR TypeError: Environment file doesn't exist: /home/vcap/app/.env
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at module.exports (/home/vcap/app/node_modules/node-env-file/lib/index.js:130:19)
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/server.js:19:2)
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at Module._compile (module.js:460:26)
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at Object.Module._extensions..js (module.js:478:10)
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at Module.load (module.js:355:32)
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at Function.Module._load (module.js:310:12)
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at Function.Module.runMain (module.js:501:10)
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at startup (node.js:129:16)
2015-11-18T19:23:56.39+0200 [App/0]      ERR     at node.js:814:3
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! Linux 3.19.0-25-generic
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! node v0.12.7
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! npm  v2.11.3
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! code ELIFECYCLE
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! locallaunch@1.0.0 start: `node server.js`
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! Exit status 1
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! 
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! Failed at the locallaunch@1.0.0 start script 'node server.js'.
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! This is most likely a problem with the locallaunch package,
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! not with npm itself.
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR!     node server.js
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! You can get their info via:
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR!     npm owner ls locallaunch
2015-11-18T19:23:56.42+0200 [App/0]      ERR npm ERR! There is likely additional logging output above.
2015-11-18T19:23:56.43+0200 [App/0]      ERR npm ERR! Please include the following file with any support request:
2015-11-18T19:23:56.43+0200 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2015-11-18T19:23:56.51+0200 [DEA/117]    ERR Instance (index 0) failed to start accepting connections
```

**Comment by rvennam** [comment]
Thanks. Fixed with 7fd415ea68e0e3d99cfde071222d231770c029b2
